In [22]:
n = 3
dp = zeros(Int, n, n)

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [23]:
# Marcamos objetivo
dp[n,n] = 1
dp

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  1

In [24]:
# Marcamos paredes
for j in 1:n
    dp[n,j] = 1
end

for j in 1:n
    dp[j,n] = 1
end

dp

3×3 Matrix{Int64}:
 0  0  1
 0  0  1
 1  1  1

In [25]:
for i in (n-1):-1:1       # i = 3, 2, 1
    for j in (n-1):-1:1   # j = 3, 2, 1
        dp[i, j] = dp[i+1, j] + dp[i, j+1]
    end
end
dp

3×3 Matrix{Int64}:
 6  3  1
 3  2  1
 1  1  1